const demoProducts=[
 {name:'Milk 1L',category:'Dairy',sell_price:1.35,stock_qty:42,cost_price:.82,low_stock_qty:10,sku:'DAI-001',barcode:'5281000000011',supplier:'Fresh Distribution'},
 {name:'Fresh Bread',category:'Bakery',sell_price:.85,stock_qty:31,cost_price:.40,low_stock_qty:8,sku:'BAK-001',barcode:'5281000000028',supplier:'Daily Goods'},
 {name:'Rice 5kg',category:'Groceries',sell_price:7.5,stock_qty:14,cost_price:5.8,low_stock_qty:5,sku:'GRO-001',barcode:'5281000000035',supplier:'Daily Goods'},
 {name:'Water 6x1.5L',category:'Beverages',sell_price:2.25,stock_qty:64,cost_price:1.4,low_stock_qty:12,sku:'BEV-001',barcode:'5281000000042',supplier:'Fresh Distribution'},
 {name:'Tuna Can',category:'Groceries',sell_price:1.10,stock_qty:7,cost_price:.72,low_stock_qty:10,sku:'GRO-002',barcode:'5281000000059',supplier:'Daily Goods'},
 {name:'Potato Chips',category:'Snacks',sell_price:.90,stock_qty:22,cost_price:.43,low_stock_qty:10,sku:'SNK-001',barcode:'5281000000066',supplier:'Daily Goods'},
 {name:'Dish Soap',category:'Household',sell_price:1.95,stock_qty:18,cost_price:1.10,low_stock_qty:6,sku:'HOU-001',barcode:'5281000000073',supplier:'Home Care Supplies'},
 {name:'Cola 330ml',category:'Beverages',sell_price:.75,stock_qty:80,cost_price:.35,low_stock_qty:20,sku:'BEV-002',barcode:'5281000000080',supplier:'Fresh Distribution'}
];
const state={mode:'demo',ready:false,sb:null,store:null,branch:null,page:'Overview',query:'',category:'All',cart:[],products:[...demoProducts],orders:[],deliveries:[],customers:[{name:'Walk-in Customer',phone:'',address:''},{name:'Nour Haddad',phone:'+961 70 123 456',address:'Hamra, Beirut'}],suppliers:[{name:'Fresh Distribution',phone:'+961 1 000 111'},{name:'Daily Goods Trading',phone:'+961 1 000 222'}],branches:[],purchaseOrders:[],refunds:[],users:[],zones:[],sessions:[]};
window.POS_STATE=state;
const pages=[['Overview','📊'],['POS Cashier','🧾'],['Online Store','🛒'],['Orders','📦'],['Delivery','🛵'],['Inventory','🏷️'],['Purchases','🧺'],['Returns','↩️'],['Branches','🏬'],['Suppliers','🚚'],['Customers','👥'],['Users & Roles','🔐'],['Cashier Closing','💵'],['Reports','📈'],['Supabase Setup','⚙️']];
const app=document.getElementById('app');
const money=n=>'USD '+Number(n||0).toFixed(2);const clean=s=>(s||'').toString().toLowerCase();const today=()=>new Date().toISOString().slice(0,10).replaceAll('-','');
function toast(t){let x=document.createElement('div');x.className='toast';x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),2600)}
function statusClass(s){s=clean(s);if(['completed','paid','delivered','accepted','received','closed','admin'].includes(s))return'green';if(['cancelled','failed','refunded'].includes(s))return'red';if(['new','pending','preparing','draft','ordered','open'].includes(s))return'amber';return'blue'}
async function connect(){try{let c=await fetch('/api/config',{cache:'no-store'}).then(r=>r.json());if(!c.ready)throw Error('Missing Supabase variables');let m=await import('https://esm.sh/@supabase/supabase-js@2.50.0');state.sb=m.createClient(c.url,c.key);state.mode='live'}catch(e){state.mode='demo';console.warn(e.message)}state.ready=true}
async function q(table,select='*'){if(!state.sb)return null;let r=await state.sb.from(table).select(select);if(r.error){console.warn(table,r.error.message);return null}return r.data||[]}
async function loadLive(){if(!state.sb)return;let stores=await q('stores');state.store=stores?.[0]||null;state.branches=await q('branches')||[];state.branch=state.branches?.[0]||null;let ps=await q('products','id,name,sku,barcode,unit,cost_price,sell_price,stock_qty,low_stock_qty,tax_rate,product_categories(name),suppliers(name)');if(ps?.length)state.products=ps.map(p=>({...p,category:p.product_categories?.name||'Uncategorized',supplier:p.suppliers?.name||''}));state.customers=await q('customers')||state.customers;state.suppliers=await q('suppliers')||state.suppliers;state.orders=await q('orders','id,order_no,source,status,subtotal,delivery_fee,grand_total,payment_status,created_at,customers(name,phone,address)')||[];state.deliveries=await q('delivery_orders','id,order_id,driver_name,status,cash_collected,delivery_fee,customer_address,orders(order_no,grand_total,status)')||[];state.purchaseOrders=await q('purchase_orders','id,po_no,status,subtotal,created_at,received_at,suppliers(name)')||[];state.refunds=await q('refunds','id,amount,reason,restock,created_at,orders(order_no)')||[];state.users=await q('app_users')||[];state.zones=await q('delivery_zones')||[];state.sessions=await q('cashier_sessions')||[]}
async function refresh(page=state.page){if(state.mode==='live')await loadLive();render(page)}
function layout(){return `<div class='layout'><aside class='sidebar'><div class='brand'><div class='logo'>AH</div><div><small>Market Suite</small><h2>Al Hashem POS</h2></div></div><nav class='nav'>${pages.map(p=>`<button class='${state.page===p[0]?'active':''}' onclick="render('${p[0]}')"><span>${p[1]}</span>${p[0]}</button>`).join('')}</nav><div class='status-card'><div class='status-row'><i class='dot ${state.mode==='live'?'live':''}'></i><div><b>${state.mode==='live'?'Live Supabase':'Demo fallback'}</b><span>${state.mode==='live'?'Reading and writing database data':'Check variables / RLS'}</span></div></div></div></aside><section class='content'><div class='topbar'><h1>${state.page}</h1><div class='top-actions'><button class='btn' onclick='exportData()'>Export Data</button><button class='btn primary' onclick="render('POS Cashier')">Open POS</button></div></div><main class='page' id='view'></main></section></div>`}
function render(page='Overview'){state.page=page;app.className='';app.innerHTML=layout();document.getElementById('view').innerHTML=views[page]();window.dispatchEvent(new Event('pos:rendered'))}
const openOrders=()=>state.orders.filter(o=>!['completed','cancelled','refunded'].includes(clean(o.status)));const revenue=()=>state.orders.filter(o=>['completed','paid'].includes(clean(o.status))).reduce((s,o)=>s+Number(o.grand_total||0),0);const profit=()=>state.orders.reduce((s,o)=>s+Number(o.grand_total||0)*.32,0);const lowStock=()=>state.products.filter(p=>Number(p.stock_qty)<=Number(p.low_stock_qty||5));const stockValue=()=>state.products.reduce((s,p)=>s+Number(p.stock_qty||0)*Number(p.cost_price||0),0);const categories=()=>['All',...new Set(state.products.map(p=>p.category||'Uncategorized'))];
function filteredProducts(){return state.products.filter(p=>(state.category==='All'||p.category===state.category)&&[p.name,p.sku,p.barcode,p.category].join(' ').toLowerCase().includes(clean(state.query)))}
function setSearch(v){state.query=v;render(state.page)}function setCat(v){state.category=v;render(state.page)}function add(i){let p=filteredProducts()[i];let c=state.cart.find(x=>(x.id&&x.id===p.id)||x.name===p.name);c?c.qty++:state.cart.push({...p,qty:1});render('POS Cashier')}function qty(i,d){state.cart[i].qty+=d;if(state.cart[i].qty<1)state.cart.splice(i,1);render('POS Cashier')}function clearCart(){state.cart=[];render('POS Cashier')}const total=()=>state.cart.reduce((s,i)=>s+Number(i.sell_price)*i.qty,0);
async function completeSale(){if(!state.cart.length)return alert('Cart empty');let discount=Number(prompt('Discount amount',0)||0);let grand=Math.max(0,total()-discount);window.POS_LAST_RECEIPT={order_no:'SALE-'+Date.now().toString().slice(-5),items:[...state.cart],subtotal:total(),discount,grand,created_at:new Date().toISOString()};if(state.mode!=='live'){state.orders.unshift({order_no:window.POS_LAST_RECEIPT.order_no,source:'pos',status:'completed',subtotal:total(),discount_total:discount,grand_total:grand,payment_status:'paid'});state.cart.forEach(c=>{let p=state.products.find(x=>x.name===c.name);if(p)p.stock_qty=Number(p.stock_qty)-c.qty});state.cart=[];toast('Demo sale completed');window.dispatchEvent(new Event('pos:sale-completed'));return render('POS Cashier')}let orderNo='POS-'+today()+'-'+Date.now().toString().slice(-5);window.POS_LAST_RECEIPT.order_no=orderNo;let r=await state.sb.from('orders').insert({store_id:state.store?.id,branch_id:state.branch?.id,order_no:orderNo,source:'pos',status:'completed',subtotal:total(),discount_total:discount,grand_total:grand,payment_status:'paid'}).select().single();if(r.error)return alert(r.error.message);await state.sb.from('order_items').insert(state.cart.map(c=>({order_id:r.data.id,product_id:c.id,product_name:c.name,qty:c.qty,unit_price:c.sell_price,cost_price:c.cost_price||0,line_total:c.sell_price*c.qty})));await state.sb.from('payments').insert({order_id:r.data.id,method:'cash',amount:grand});for(const c of state.cart){await state.sb.from('products').update({stock_qty:Number(c.stock_qty)-c.qty}).eq('id',c.id);await state.sb.from('stock_movements').insert({product_id:c.id,movement_type:'sale',qty_change:-c.qty,note:orderNo})}state.cart=[];toast('Live sale saved');window.dispatchEvent(new Event('pos:sale-completed'));await refresh('POS Cashier')}
async function createOnlineOrder(){let sample=state.products.slice(0,3);let subtotal=sample.reduce((s,p)=>s+Number(p.sell_price),0);let delivery_fee=Number(state.zones[0]?.delivery_fee||1.5);let grand=subtotal+delivery_fee;if(state.mode!=='live'){state.orders.unshift({order_no:'WEB-'+Date.now().toString().slice(-5),source:'online',status:'new',subtotal,delivery_fee,grand_total:grand,payment_status:'unpaid',customers:{name:'Demo Customer',phone:'+961 70 000 000',address:'Beirut'}});toast('Demo online order created');return render('Online Store')}let cust=state.customers.find(c=>c.name!=='Walk-in Customer')||state.customers[0];let r=await state.sb.from('orders').insert({store_id:state.store?.id,branch_id:state.branch?.id,customer_id:cust?.id,order_no:'WEB-'+today()+'-'+Date.now().toString().slice(-5),source:'online',status:'new',subtotal,delivery_fee,grand_total:grand,payment_status:'unpaid'}).select().single();if(r.error)return alert(r.error.message);await state.sb.from('order_items').insert(sample.map(p=>({order_id:r.data.id,product_id:p.id,product_name:p.name,qty:1,unit_price:p.sell_price,cost_price:p.cost_price||0,line_total:p.sell_price})));toast('Live online order created');await refresh('Orders')}
async function updateOrder(id,status){if(state.mode==='live'){let r=await state.sb.from('orders').update({status}).eq('id',id);if(r.error)return alert(r.error.message);toast('Order updated');await refresh('Orders')}else{let o=state.orders.find(x=>(x.id||x.order_no)===id);if(o)o.status=status;render('Orders')}}
async function sendDelivery(i){let o=openOrders()[i]||state.orders[i];if(!o)return;if(state.mode!=='live'){state.deliveries.unshift({id:'DEL-'+Date.now().toString().slice(-4),orders:{order_no:o.order_no,grand_total:o.grand_total},driver_name:'Unassigned',status:'pending',customer_address:o.customers?.address||'Beirut',cash_collected:o.grand_total});toast('Demo delivery created');return render('Delivery')}let r=await state.sb.from('delivery_orders').insert({order_id:o.id,driver_name:'Unassigned',customer_address:o.customers?.address||'',delivery_fee:o.delivery_fee||0,status:'pending',cash_collected:o.grand_total}).select().single();if(r.error)return alert(r.error.message);await state.sb.from('orders').update({status:'preparing'}).eq('id',o.id);toast('Delivery created');await refresh('Delivery')}
async function setDelivery(i,status){let d=state.deliveries[i];if(!d)return;if(state.mode==='live'){let r=await state.sb.from('delivery_orders').update({status}).eq('id',d.id);if(r.error)return alert(r.error.message);if(status==='delivered'&&d.order_id)await state.sb.from('orders').update({status:'completed',payment_status:'paid'}).eq('id',d.order_id);toast('Delivery updated');await refresh('Delivery')}else{d.status=status;if(status==='delivered')d.orders.status='completed';render('Delivery')}}
async function addCustomer(){let name=prompt('Customer name');if(!name)return;let phone=prompt('Phone')||'';let address=prompt('Address')||'';if(state.mode==='live'){let r=await state.sb.from('customers').insert({store_id:state.store?.id,name,phone,address}).select().single();if(r.error)return alert(r.error.message);toast('Customer added');await refresh('Customers')}else{state.customers.push({name,phone,address});render('Customers')}}
async function addProduct(){let name=prompt('Product name');if(!name)return;let sell_price=Number(prompt('Selling price')||0);let stock_qty=Number(prompt('Stock qty')||0);if(state.mode==='live'){let r=await state.sb.from('products').insert({store_id:state.store?.id,name,sell_price,stock_qty,cost_price:0,low_stock_qty:5}).select().single();if(r.error)return alert(r.error.message);toast('Product added');await refresh('Inventory')}else{state.products.push({name,category:'New',sell_price,stock_qty,cost_price:0,low_stock_qty:5});render('Inventory')}}
async function receiveStock(){let p=state.products[0];if(!p)return;let qtyNum=Number(prompt('Receive quantity for '+p.name,10)||0);if(!qtyNum)return;if(state.mode==='live'){await state.sb.from('products').update({stock_qty:Number(p.stock_qty)+qtyNum}).eq('id',p.id);await state.sb.from('stock_movements').insert({product_id:p.id,movement_type:'purchase',qty_change:qtyNum,note:'Quick receiving'});toast('Stock received');await refresh('Purchases')}else{p.stock_qty+=qtyNum;toast('Demo stock received');render('Purchases')}}
async function createPO(){let supplier=state.suppliers[0],p=state.products[0],amount=Number(p?.cost_price||1)*10;if(state.mode==='live'){let r=await state.sb.from('purchase_orders').insert({store_id:state.store?.id,supplier_id:supplier?.id,po_no:'PO-'+today()+'-'+Date.now().toString().slice(-4),status:'ordered',subtotal:amount,notes:'Auto test PO'}).select().single();if(r.error)return alert(r.error.message);await state.sb.from('purchase_order_items').insert({purchase_order_id:r.data.id,product_id:p?.id,product_name:p?.name||'Item',qty_ordered:10,unit_cost:p?.cost_price||1,line_total:amount});toast('Purchase order created');await refresh('Purchases')}else{state.purchaseOrders.unshift({po_no:'PO-DEMO-'+Date.now().toString().slice(-4),status:'ordered',subtotal:amount,suppliers:{name:supplier?.name||'Supplier'}});render('Purchases')}}
async function refundOrder(){let o=state.orders.find(x=>clean(x.status)==='completed')||state.orders[0];if(!o)return alert('No order to refund');let amount=Number(prompt('Refund amount',o.grand_total)||0);let reason=prompt('Refund reason','Customer return')||'Customer return';if(state.mode==='live'){let r=await state.sb.from('refunds').insert({order_id:o.id,amount,reason,restock:true}).select().single();if(r.error)return alert(r.error.message);await state.sb.from('orders').update({status:'refunded',payment_status:'refunded'}).eq('id',o.id);toast('Refund saved');await refresh('Returns')}else{state.refunds.unshift({amount,reason,orders:{order_no:o.order_no},created_at:new Date().toISOString()});o.status='refunded';render('Returns')}}
async function closeShift(){let expected=revenue()+100,actual=Number(prompt('Actual cash counted',expected)||expected);if(state.mode==='live'){let r=await state.sb.from('cashier_sessions').insert({branch_id:state.branch?.id,cashier_name:'Demo Cashier',opening_cash:100,expected_cash:expected,actual_cash:actual,difference:actual-expected,status:'closed',closed_at:new Date().toISOString()});if(r.error)return alert(r.error.message);toast('Shift closed');await refresh('Cashier Closing')}else{state.sessions.unshift({cashier_name:'Demo Cashier',opening_cash:100,expected_cash:expected,actual_cash:actual,difference:actual-expected,status:'closed'});render('Cashier Closing')}}
function productGrid(){return `<div class='toolbar'><input class='input' style='max-width:360px' placeholder='Search name, SKU, barcode...' value='${state.query}' oninput='setSearch(this.value)'><select class='select' style='max-width:210px' onchange='setCat(this.value)'>${categories().map(c=>`<option ${state.category===c?'selected':''}>${c}</option>`).join('')}</select></div><div class='products'>${filteredProducts().map((p,i)=>`<button class='product' onclick='add(${i})'><div class='picon'>🏷️</div><h4>${p.name}</h4><small>${p.category||'Uncategorized'} • ${p.sku||'No SKU'}</small><div class='price'><b>${money(p.sell_price)}</b><span class='stock ${Number(p.stock_qty)<=Number(p.low_stock_qty||5)?'low':''}'>${p.stock_qty} left</span></div></button>`).join('')}</div>`}
const tableRows=()=>state.products.map(p=>`<tr><td>${p.name}</td><td>${p.sku||''}</td><td>${p.barcode||''}</td><td>${p.category||''}</td><td>${p.supplier||''}</td><td><span class='badge ${Number(p.stock_qty)<=Number(p.low_stock_qty||5)?'red':'green'}'>${p.stock_qty}</span></td><td>${money(p.cost_price)}</td><td>${money(p.sell_price)}</td><td>${money(Number(p.sell_price)-Number(p.cost_price||0))}</td></tr>`).join('');
const views={
Overview(){return `<div class='notice'><b>No QR menu and no restaurant table flow.</b> Advanced market operating system: POS, online orders, delivery, inventory, purchases, returns, users, branches, closing, and analytics.</div><div class='cards'><div class='card'><label>Today Sales</label><strong>${money(revenue())}</strong><span>${state.orders.filter(o=>clean(o.status)==='completed').length} completed sales</span></div><div class='card'><label>Open Orders</label><strong>${openOrders().length}</strong><span>Online and delivery queue</span></div><div class='card'><label>Low Stock</label><strong>${lowStock().length}</strong><span>Products need reorder</span></div><div class='card'><label>Stock Value</label><strong>${money(stockValue())}</strong><span>Estimated cost value</span></div></div><div class='grid-2'><section class='panel'><div class='section-title'><h3>Open Orders</h3><button class='btn' onclick="render('Orders')">View All</button></div>${openOrders().slice(0,4).map((o,i)=>`<div class='drawer-row'><div><b>${o.order_no}</b><div class='muted'>${o.source} • ${o.customers?.name||'Customer'} • ${money(o.grand_total)}</div></div><button class='btn' onclick='sendDelivery(${i})'>Delivery</button></div>`).join('')||'<p class=muted>No open orders.</p>'}</section><section class='panel'><div class='section-title'><h3>Low Stock Alerts</h3><button class='btn' onclick="render('Inventory')">Inventory</button></div>${lowStock().map(p=>`<div class='drawer-row'><div><b>${p.name}</b><div class='muted'>Minimum ${p.low_stock_qty} • ${p.supplier||''}</div></div><span class='badge red'>${p.stock_qty}</span></div>`).join('')||'<p class=muted>No low stock alerts.</p>'}</section></div>`},
'POS Cashier'(){return `<div class='grid-main'><section class='panel'><div class='section-title'><h3>Fast Product Search</h3><span class='badge blue'>Barcode ready</span></div>${productGrid()}</section><aside class='panel'><div class='section-title'><h3>Current Cart</h3><button class='btn' onclick='clearCart()'>Clear</button></div><div class='cart-list'>${state.cart.map((c,i)=>`<div class='cart-item'><div><b>${c.name}</b><div class='muted'>${money(c.sell_price)} each</div></div><div><div class='qty'><button onclick='qty(${i},-1)'>−</button><b>${c.qty}</b><button onclick='qty(${i},1)'>+</button></div><b>${money(c.sell_price*c.qty)}</b></div></div>`).join('')||'<p class=muted>No items in cart.</p>'}</div><div class='line'><span>Subtotal</span><b>${money(total())}</b></div><div class='line'><span>Total before discount</span><b>${money(total())}</b></div><button class='btn primary' style='width:100%;margin-top:12px' onclick='completeSale()'>Complete Sale</button></aside></div>`},
'Online Store'(){return `<div class='section-title'><div><h3>Customer Online Ordering</h3><p class='muted'>Public ordering flow for delivery or pickup. No QR menu.</p></div><button class='btn primary' onclick='createOnlineOrder()'>Create Test Online Order</button></div><div class='storefront'>${state.products.slice(0,8).map(p=>`<div class='store-card'><span class='badge blue'>${p.category||'Product'}</span><h4>${p.name}</h4><p class='muted'>${p.sku||''} • Stock ${p.stock_qty}</p><h2>${money(p.sell_price)}</h2><button class='btn'>Add to online cart</button></div>`).join('')}</div>`},
Orders(){return `<div class='section-title'><h3>Orders Command Center</h3><button class='btn primary' onclick='createOnlineOrder()'>New Test Order</button></div>${state.orders.map((o,i)=>`<div class='order'><div><h4>${o.order_no}</h4><div class='badges'><span class='badge blue'>${o.source}</span><span class='badge ${statusClass(o.status)}'>${o.status}</span><span class='badge'>${o.payment_status||'unpaid'}</span></div><p class='muted'>${o.customers?.name||'Walk-in'} • ${o.customers?.phone||''} • ${money(o.grand_total)}</p></div><div class='toolbar'><button class='btn' onclick="updateOrder('${o.id||o.order_no}','accepted')">Accept</button><button class='btn' onclick='sendDelivery(${i})'>Delivery</button><button class='btn primary' onclick="updateOrder('${o.id||o.order_no}','completed')">Complete</button></div></div>`).join('')||'<p class=muted>No orders found.</p>'}`},
Delivery(){return `<div class='section-title'><h3>Delivery Board</h3><button class='btn' onclick="render('Orders')">Create from order</button></div>${state.deliveries.map((d,i)=>`<div class='order'><div><h4>${d.orders?.order_no||d.id}</h4><div class='badges'><span class='badge ${statusClass(d.status)}'>${d.status}</span><span class='badge'>${d.driver_name||'Unassigned'}</span></div><p class='muted'>${d.customer_address||'No address'} • Cash ${money(d.cash_collected||d.orders?.grand_total)}</p></div><div class='toolbar'><button class='btn' onclick="setDelivery(${i},'assigned')">Assign</button><button class='btn' onclick="setDelivery(${i},'out_for_delivery')">Out</button><button class='btn primary' onclick="setDelivery(${i},'delivered')">Delivered</button></div></div>`).join('')||'<p class=muted>No delivery orders yet.</p>'}`},
Inventory(){return `<div class='section-title'><h3>Inventory Management</h3><button class='btn primary' onclick='addProduct()'>Add Product</button></div><div class='panel'>${productGrid()}</div><div class='table-wrap'><table><thead><tr><th>Product</th><th>SKU</th><th>Barcode</th><th>Category</th><th>Supplier</th><th>Stock</th><th>Cost</th><th>Sell</th><th>Margin</th></tr></thead><tbody>${tableRows()}</tbody></table></div>`},
Purchases(){return `<div class='section-title'><h3>Purchase Orders & Receiving</h3><div class='toolbar'><button class='btn' onclick='receiveStock()'>Quick Receive Stock</button><button class='btn primary' onclick='createPO()'>Create Test PO</button></div></div><div class='grid-2'><section class='panel'><h3>Purchase Orders</h3>${state.purchaseOrders.map(p=>`<div class='drawer-row'><div><b>${p.po_no}</b><div class='muted'>${p.suppliers?.name||'Supplier'} • ${p.status}</div></div><b>${money(p.subtotal)}</b></div>`).join('')||'<p class=muted>No purchase orders yet.</p>'}</section><section class='panel'><h3>Receiving Guide</h3><p class='muted'>Use Quick Receive Stock to add stock and create a purchase stock movement. The full PO tables are ready in Supabase.</p></section></div>`},
Returns(){return `<div class='section-title'><h3>Returns & Refunds</h3><button class='btn primary' onclick='refundOrder()'>Refund Latest Sale</button></div><div class='panel'>${state.refunds.map(r=>`<div class='drawer-row'><div><b>${r.orders?.order_no||'Refund'}</b><div class='muted'>${r.reason} • Restock: ${r.restock?'Yes':'No'}</div></div><b>${money(r.amount)}</b></div>`).join('')||'<p class=muted>No refunds yet.</p>'}</div>`},
Branches(){return `<div class='section-title'><h3>Branches & Stock Transfers</h3><button class='btn'>Create Transfer</button></div><div class='grid-2'>${(state.branches.length?state.branches:[state.branch||{name:'Main Branch',address:'Main Street'}]).map(b=>`<div class='panel'><h3>${b.name}</h3><p class='muted'>${b.address||''}</p><div class='line'><span>Status</span><b>${b.is_active===false?'Inactive':'Active'}</b></div></div>`).join('')}</div>`},
Suppliers(){return `<div class='section-title'><h3>Supplier Directory</h3><button class='btn'>Add Supplier</button></div><div class='grid-2'>${state.suppliers.map(s=>`<div class='panel'><h3>${s.name}</h3><p class='muted'>${s.phone||''} ${s.email||''}</p><div class='line'><span>Balance</span><b>${money(s.balance||0)}</b></div></div>`).join('')}</div>`},
Customers(){return `<div class='section-title'><h3>Customers</h3><button class='btn primary' onclick='addCustomer()'>Add Customer</button></div><div class='grid-2'>${state.customers.map(c=>`<div class='panel'><h3>${c.name}</h3><p class='muted'>${c.phone||''}</p><p>${c.address||'Walk-in customer'}</p></div>`).join('')}</div>`},
'Users & Roles'(){return `<div class='section-title'><h3>Users & Permissions</h3><button class='btn'>Invite User</button></div><div class='grid-2'>${(state.users.length?state.users:[{full_name:'Admin User',email:'admin@alhashem.test',role:'admin'},{full_name:'Cashier User',email:'cashier@alhashem.test',role:'cashier'}]).map(u=>`<div class='panel'><h3>${u.full_name}</h3><p class='muted'>${u.email||''}</p><span class='badge ${statusClass(u.role)}'>${u.role}</span></div>`).join('')}</div>`},
'Cashier Closing'(){let expected=revenue()+100;return `<div class='panel'><h3>Shift Closing</h3><div class='line'><span>Opening Cash</span><b>USD 100.00</b></div><div class='line'><span>Cash Sales</span><b>${money(revenue())}</b></div><div class='line'><span>Expected Cash</span><b>${money(expected)}</b></div><button class='btn primary' onclick='closeShift()'>Close Shift</button></div><div class='panel'><h3>Past Sessions</h3>${state.sessions.map(s=>`<div class='drawer-row'><div><b>${s.cashier_name}</b><div class='muted'>${s.status}</div></div><b>${money(s.difference||0)}</b></div>`).join('')||'<p class=muted>No sessions yet.</p>'}</div>`},
Reports(){return `<div class='cards'><div class='card'><label>Total Revenue</label><strong>${money(revenue())}</strong><span>Completed sales</span></div><div class='card'><label>Gross Profit Estimate</label><strong>${money(profit())}</strong><span>Estimated MVP calculation</span></div><div class='card'><label>Deliveries</label><strong>${state.deliveries.length}</strong><span>All delivery records</span></div><div class='card'><label>Inventory Value</label><strong>${money(stockValue())}</strong><span>Cost value</span></div></div><div class='grid-2'><section class='panel'><h3>Sales by Source</h3><div class='line'><span>POS</span><b>${state.orders.filter(o=>o.source==='pos').length}</b></div><div class='line'><span>Online</span><b>${state.orders.filter(o=>o.source==='online').length}</b></div></section><section class='panel'><h3>Operational Alerts</h3><div class='line'><span>Low stock</span><b>${lowStock().length}</b></div><div class='line'><span>Open orders</span><b>${openOrders().length}</b></div><div class='line'><span>Refunds</span><b>${state.refunds.length}</b></div></section></div>`},
'Supabase Setup'(){return `<div class='panel'><h3>Connection Status: ${state.mode==='live'?'Live Supabase connected':'Demo fallback'}</h3><p class='muted'>Run supabase-advanced-upgrade.sql after the base schema to unlock purchases, refunds, users, branches, zones, and transfers.</p><button class='btn primary' onclick="refresh('Overview')">Reload Live Data</button></div><div class='panel'><h3>Production hardening</h3><p>Replace demo open RLS policies with authenticated role-based policies before real client data.</p></div>`}
};
function exportData(){let data={products:state.products,orders:state.orders,deliveries:state.deliveries,purchases:state.purchaseOrders,refunds:state.refunds,customers:state.customers};let blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='al-hashem-pos-export.json';a.click()}
Object.assign(window,{render,setSearch,setCat,add,qty,clearCart,completeSale,createOnlineOrder,updateOrder,sendDelivery,setDelivery,addCustomer,addProduct,receiveStock,createPO,refundOrder,closeShift,refresh,exportData});
(async()=>{app.innerHTML=layout();await connect();await refresh('Overview')})();
