const HOLD_KEY='al_hashem_held_carts';
const getState=()=>window.POS_STATE||{};
const money=n=>'USD '+Number(n||0).toFixed(2);
function held(){try{return JSON.parse(localStorage.getItem(HOLD_KEY)||'[]')}catch{return[]}}
function saveHeld(x){localStorage.setItem(HOLD_KEY,JSON.stringify(x))}
function modal(html){let wrap=document.createElement('div');wrap.className='pro-modal';wrap.innerHTML=`<div class='pro-card'>${html}</div>`;wrap.addEventListener('click',e=>{if(e.target===wrap)wrap.remove()});document.body.appendChild(wrap);return wrap}
function closeBtn(){return `<button class='pro-close' onclick='this.closest(".pro-modal").remove()'>Close</button>`}
function addDock(){if(document.getElementById('proDock'))return;let dock=document.createElement('div');dock.id='proDock';dock.className='pro-dock';dock.innerHTML=`<button onclick='proCommand()'>⌘ Command</button><button onclick='holdCart()'>Hold Cart</button><button onclick='showHeldCarts()'>Held</button><button onclick='showReceipt()'>Receipt</button><button onclick='showManagerPulse()'>Pulse</button>`;document.body.appendChild(dock)}
function holdCart(){let s=getState();if(!s.cart||!s.cart.length)return alert('Cart is empty');let name=prompt('Hold name / customer','Held Cart '+new Date().toLocaleTimeString());if(!name)return;let list=held();list.unshift({id:Date.now(),name,items:s.cart,created_at:new Date().toISOString()});saveHeld(list);if(window.clearCart)window.clearCart();alert('Cart held')}
function showHeldCarts(){let list=held();modal(`<div class='pro-head'><h2>Held Carts</h2>${closeBtn()}</div><div class='held-list'>${list.map(h=>`<div class='held'><div><b>${h.name}</b><div class='muted'>${h.items.length} items • ${new Date(h.created_at).toLocaleString()}</div></div><button class='btn primary' onclick='resumeHeld(${h.id})'>Resume</button></div>`).join('')||'<p class=muted>No held carts.</p>'}</div>`)}
function resumeHeld(id){let s=getState(),list=held(),h=list.find(x=>x.id===id);if(!h)return;s.cart.splice(0,s.cart.length,...h.items);saveHeld(list.filter(x=>x.id!==id));document.querySelector('.pro-modal')?.remove();window.render&&window.render('POS Cashier')}
function receiptHtml(r){r=r||window.POS_LAST_RECEIPT||{};let items=r.items||[];return `<div class='receipt'><h3>Al Hashem Market</h3><p style='text-align:center'>POS Receipt<br>${r.order_no||'No receipt'}<br>${new Date(r.created_at||Date.now()).toLocaleString()}</p>${items.map(i=>`<div class='row'><span>${i.qty||1} x ${i.name}</span><b>${money((i.sell_price||0)*(i.qty||1))}</b></div>`).join('')}<div class='row'><span>Subtotal</span><b>${money(r.subtotal||0)}</b></div><div class='row'><span>Discount</span><b>${money(r.discount||0)}</b></div><div class='row'><span>Total</span><b>${money(r.grand||0)}</b></div><p style='text-align:center'>Thank you</p></div>`}
function showReceipt(){modal(`<div class='pro-head'><h2>Receipt Preview</h2><div><button class='btn primary' onclick='printReceipt()'>Print</button>${closeBtn()}</div></div><div id='receiptPreview'>${receiptHtml()}</div>`)}
function printReceipt(){let r=document.getElementById('receiptPreview')?.innerHTML||receiptHtml();let w=window.open('','_blank','width=380,height=700');w.document.write(`<html><head><title>Receipt</title><style>body{font-family:monospace}.row{display:flex;justify-content:space-between;border-bottom:1px dashed #999;padding:6px 0}h3,p{text-align:center}</style></head><body>${r}</body></html>`);w.document.close();w.print()}
function showManagerPulse(){let s=getState();let revenue=(s.orders||[]).filter(o=>['completed','paid'].includes((o.status||'').toLowerCase())).reduce((a,o)=>a+Number(o.grand_total||0),0);let low=(s.products||[]).filter(p=>Number(p.stock_qty)<=Number(p.low_stock_qty||5)).length;let open=(s.orders||[]).filter(o=>!['completed','cancelled','refunded'].includes((o.status||'').toLowerCase())).length;let del=(s.deliveries||[]).length;modal(`<div class='pro-head'><h2>Manager Pulse</h2>${closeBtn()}</div><div class='kpi-strip'><div><small>Revenue</small><h3>${money(revenue)}</h3></div><div><small>Open Orders</small><h3>${open}</h3></div><div><small>Low Stock</small><h3>${low}</h3></div><div><small>Deliveries</small><h3>${del}</h3></div></div><p class='muted'>This panel gives managers a quick operational snapshot from the current live/demo state.</p>`)}
const commands=[['Open POS','POS Cashier'],['Open Orders','Orders'],['Open Inventory','Inventory'],['Open Purchases','Purchases'],['Open Returns','Returns'],['Open Delivery','Delivery'],['Open Reports','Reports'],['Open Users','Users & Roles']];
function proCommand(){modal(`<div class='pro-head'><h2>Command Palette</h2>${closeBtn()}</div><input class='cmd-input' id='cmdSearch' placeholder='Type a command...'><div class='cmd-list' id='cmdList'>${commands.map(c=>`<button onclick="document.querySelector('.pro-modal').remove();render('${c[1]}')">${c[0]}</button>`).join('')}</div>`);let input=document.getElementById('cmdSearch');input?.focus();input?.addEventListener('input',()=>{let q=input.value.toLowerCase();document.getElementById('cmdList').innerHTML=commands.filter(c=>c[0].toLowerCase().includes(q)).map(c=>`<button onclick="document.querySelector('.pro-modal').remove();render('${c[1]}')">${c[0]}</button>`).join('')})}
window.addEventListener('pos:sale-completed',()=>setTimeout(showReceipt,350));
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='p'){e.preventDefault();showReceipt()}if((e.ctrlKey||e.metaKey)&&e.shiftKey&&e.key.toLowerCase()==='k'){e.preventDefault();proCommand()}});
setInterval(addDock,700);
Object.assign(window,{holdCart,showHeldCarts,resumeHeld,showReceipt,printReceipt,showManagerPulse,proCommand});